### PR TITLE
Create car_maxus_edeliver3.png

### PR DESCRIPTION
**Pull request by KilveEng**
add image to maxus eDeliver3

### CODE REVIEW

**Comment by glynhudson** [comment]
Nice work, it would be great to get the Maxus images also added to the Android app. Here's an example of the MG ZS: https://github.com/openvehicles/Open-Vehicle-Android/commit/495e1821c2442cee48846263a7b1972142bf323b

I'm happy to help to add the images to the Android app, but I would need help with graphic design. 

Is the Maxus now supported?

**Comment by KilveEng** [comment]
Morning Glyn,
I hope the graphic is fine, I did message you on slack
The basic support is there and don’t seem to have any bugs, but as it’s only me doing the work and testing it’s a lot of head scratching! 
Re app Not sure what else I need to add to the iOS so any guidance appreciated, happy to help with graphics, if I know what you need and will help to know what I need to do.

Regards
Shane

**Comment by KilveEng** [comment]
hi, if this is correct can it be pulled? if not can someone point out what need changing, first attempt at iOS bit

**Comment by markwj** [comment]
Can you modify this pull request to only include the actual three image additions? I can then bring them in easier, with less conflicts to the existing resources.

**Comment by KilveEng** [comment]
was easier for me to close and make a new pull request hope the new one is what you want?

**Comment by KilveEng** [comment]
Hi Mark, 

I closed that pull request and opened a new with just the images added in the directories is that what you what?

Shane

**Pull request closed without merging**
