### PR TITLE
Maxus eDeliver3 images

### PR DESCRIPTION
**Pull request by KilveEng**

### CODE REVIEW

**Comment by markwj** [comment]
Merged in the images. I will handle the other changes necessary to get these integrated.

**Comment by markwj** [comment]
This is in 1.8.5 (20210412). Going through App Store review process now, and estimate release to TestFlight early testers within 24 hours.

**Comment by KilveEng** [comment]
Cool thanks Mark
Can I have an invite to test on TestFlight 

Regards
Shane Hunns

**Comment by markwj** [comment]
> Cool thanks Mark Can I have an invite to test on TestFlight Regards Shane Hunns
> […](#)

Here is the public TestFlight link:

https://testflight.apple.com/join/05tfPlqR

But you need to wait for Apple's pre-approval. Should be <24hours if no issues found.

**Comment by KilveEng** [comment]
Thanks Mark :-)

Regards
Shane

**Pull request merged**
